# Generated by Django 4.2.1 on 2023-06-02 22:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_applicantdetail_employmentstrength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantdetail',
            name='appliacant_image',
        ),
        migrations.AddField(
            model_name='applicantdetail',
            name='applicant_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
