# Generated by Django 4.2.1 on 2023-06-02 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_applicantdetail_appliacant_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicantdetail',
            options={'ordering': ('albumSerialNumber',), 'verbose_name': 'Applicant Details', 'verbose_name_plural': 'Applicant Details'},
        ),
    ]
