# Generated by Django 4.2.1 on 2023-06-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_applicantdetail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetail',
            name='albumSerialNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
